### PR TITLE
Push notification passphrase

### PR DESCRIPTION
**Pull request by avinoth**
Support Push notification passphrase as config attribute.
Merge last-modified header feature from #26

### CODE REVIEW

**Comment by frozon** [comment]
looks LGTM if you could also review @lgleasain

**Comment by avinoth** [comment]
@frozon Something to check here ?

https://github.com/frozon/passbook/compare/master...lgleasain:master

**Comment by rmosolgo** [comment]
:+1: I was getting an error from apple for not including this header, but updating to this branch worked for me. 

I also ran into the passphrase issue, but I worked around it by using Grocer's notification API directly: 

```ruby
    pusher = Grocer.pusher(
      certificate: Passbook.notification_cert,
      passphrase:  Passbook.p12_password,
      gateway: Rails.env.test? ? "localhost" : "gateway.push.apple.com",
    )

    PassbookDevice.find_each do |device|
      notification = Grocer::PassbookNotification.new(device_token: device.push_token)
      pusher.push(notification)
    end
```

Thanks for pushing this fix, I hope it can be merged soon!

**Comment by avinoth** [comment]
@frozon Changed the way empty passphrase is handled and squashed the commits. :+1:

**Comment by frozon** [comment]
Thanks for your work on it

**Pull request merged**
